### ISSUE TITLE
Map page popup issues

### ISSUE THREAD

**Issue by andygup** [Esri/nearby-javascript#20]
When logged in, there are several issues with the popup on the map result page.

To reproduce:
1. Run app locally and log in
2. Click on an item in the list
3. Go back to home page/list
4. Select another item in the list
5. Repeat steps 2 - 4

There are several issues that I'm seeing:

- On the very first list selection I get a valid popup that automatically opens when the map page loads:

![image](https://user-images.githubusercontent.com/510440/52816929-91f09400-305f-11e9-9f35-09310f28e62c.png)

- After that sometimes the popup at the bottom of the map window doesn't inflate?

![image](https://user-images.githubusercontent.com/510440/52816231-0d514600-305e-11e9-8ebe-08b27aab5993.png)

- Sometimes there's neither an icon or popup?

- And sometimes there is an icon but no popup?

![image](https://user-images.githubusercontent.com/510440/52817589-8736fe80-3061-11e9-9cc2-6e837dc101a5.png)

**Comment by odoe** [comment]
This should be fixed in latest release.
https://github.com/Esri/nearby-javascript/commit/b9c221fe08b85aa7f3552b5ba0655cf9523962c1

There is a slight delay in route transitions, where the map is still doing stuff to repopulate the items in the FeatureLayer. I can't quite catch the sequence of events, so I had to add a little debounce to opening popups in this mode. There is no delay when both map and list are shown though.

**Comment by andygup** [comment]
LGTM!
